config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: "homes#top"
get '/home/about' => 'homes#about', as:"about"
delete 'books/:id' => 'books#destroy', as: 'destroy_book'

  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:show, :edit, :index, :update]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    
    has_one_attached :image
    belongs_to :user
    
    def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
    end
  
  
   validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :books, dependent: :destroy
         
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  validates :name, length: { maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: { maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!, except: [:top, :about]
before_action :configure_permitted_parameters, if: :devise_controller?

 def after_sign_in_path_for(resource)
    user_path(resource)
 end
 
 def after_sign_out_path_for(resource)
    root_path
 end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :is_matching_login_user, only: [:edit, :update, :destroy]
    
    def new
    @book = Book.new
    end
    
    # 投稿データの保存
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all 
      @user = current_user
      @user_id = current_user.id
      render :index
    end
  end
  
  
  def index
    @book = Book.new
    @books = Book.all 
    @user = current_user
    @user_id = current_user.id
  end

  def edit
    is_matching_login_user
    @book = Book.find(params[:id])
  end
  

 def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      flash[:notice] = "Edit was unsuccessful."
      render :edit
    end
 end


  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end
  
  
  def show
     @book = Book.new
     @book_detail = Book.find(params[:id])
     @user = @book_detail.user
  end
  
  # 投稿データのストロングパラメータ
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

 def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
 end


  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end
    
    def about
        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user1, only: [:edit, :update,]
    
  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books 
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def index
    @user = current_user
    @book = Book.new
    @books = @user.books
    @users = User.all
  end

 def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
 end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def is_matching_login_user1
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
  <p id="notice"></p>
  <div class-"container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        
<h1>Editing Book</h1>


<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @book do |f| %>
<div>
  <h4>Title</h4>
  <%= f.text_field :title %>
</div>
<div>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
</div>
<div>
  <%= f.submit "Update Book", class:"btn btn-success" %>
</div>
  
<% end %>

<%= link_to "Show", book_path(@book.id) %>
|
<%= link_to "Back", books_path %>

     </div>
   </div>
 </div>
</main>

app/views/books/index.html.erb
<main>
  
<div class="container px-5 px-sm-0">
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list', user: @user, book: @book%>
    </div>
    <div class="col-md-8 offset-md-1">
      <!-- ユーザーの投稿一覧 -->

      <h1>Books</h1>
      <table class="table table-hover table-inverse">
          <thead>
              <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Opinion</th>
                  <th colspan="3"></th>
              </tr>
              </thead>
              
              
              <tbody>
                  
      <% @books.each do |book| %>
      
      <tr>
        <td><%= link_to user_path(book.user_id) do %>
          <%=image_tag book.user.get_profile_image(100,100) %>
        <% end %>
        </td>
        <td><%=link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
        </tr>
      <% end %>
      
      </tbody>
      </table>
    </div>
  </div>
</div>
</div>
</main>

app/views/books/new.html.erb
<%= render 'users/list', user: @user, book: @book%>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h1>New book</h1>
<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body%>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<main>
    
<div class="container px-5 px-sm-0">
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/list', user: @user, book: @book%>
    </div>
    <div class="col-md-8 offset-md-1">
      <!-- ユーザーの投稿一覧 -->

      <h1>Book detail</h1>
      <table class="table table-hover table-inverse">
          <thead>
              <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Opinion</th>
                  <th colspan="3"></th>
              </tr>
              </thead>
              
              
              <tbody>
                
      <tr>
        <%= link_to book_path(@book_detail.id) do %>
          <!--%= image_tag book.get_image %-->
        <% end %>
        <td><%= image_tag @book_detail.user.get_profile_image(100,100) %>
        <br><%= link_to @book_detail.user.name, user_path(@book_detail.user.id) %>
        </td>
        <td><%=link_to @book_detail.title, book_path(@book_detail.id) %></td>
        <td><%= @book_detail.body %></td>
        <% if @book_detail.user == current_user %>
        <td><%= link_to "Edit", edit_book_path(@book_detail.id), class: "btn btn-sm btn-success" %></td>
        <td><%= link_to "Destroy", destroy_book_path(@book_detail.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-danger" %></td>
        <% end %>
      </tr>
      
      </tbody>
      </table>
    </div>
  </div>
</div>
</div>
</main>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
    <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

<h1>welcome to <i class="fa-solid fa-book"></i>Bookers !
</h1>

app/views/homes/top.html.erb
<main>
    
<p id="notice"></p>
<div class="container">
    <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

<h1>welcome to <i class="fa-solid fa-book"></i>Bookers !!
</h1>

<p>In <i class="fa-solid fa-book"></i>Bookers,</p>
<p>you can share and exchange your opinions , inpressions , and emotions</p>

<p>about various books!</p>

    <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
            <a class="btn btn-info btn-sm btn-block md-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
    
        <div class-"row">
        <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
    </div>
</div>
</div>
</div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class-"fontawesome-i2svg-active fontawesome-i2svg-complete">
  <head>
    <title>Bookers2App</title>
 <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/4d2e5b0d3d.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class-"container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            
            
              <% if user_signed_in? %>
              
              
              <li>
                <%= link_to user_path(current_user.id), class:"nav-link text-light" do %>
                 <i class="fa-solid fa-home"></i>
                Home
                <% end %>
              </li>
              
              <li>
                <%= link_to users_path, class:"nav-link text-light" do %>
                <i class="fa-solid fa-users"></i>
                Users
                <% end %>
              </li>
              
              <li>
                <%= link_to books_path, class:"nav-link text-light" do %>
                <i class="fa-solid fa-book-open"></i>
                Books
                <% end %>
              </li>
              
              <li>
                <%= link_to destroy_user_session_path, class:"nav-link text-light", method: :delete do %>
                 <i class="fa-solid fa-sign-out-alt"></i>
                Log out
                <% end %>
              </li>

              
               <% else %>
               
               
               <li>
                <%= link_to root_path, class:"nav-link text-light" do %>
                 <i class="fa-solid fa-home"></i>
                Home
                <% end %>
              </li>
              
              <li>
                <%= link_to about_path, class:"nav-link text-light" do %>
                  <i class="fa-solid fa-link"></i>
                  About
                <% end %>
              </li>
              
              <li>
                <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
                  <i class="fa-solid fa-user-plus"></i>
                  Sign up
                  <% end %>
              </li>
              
              <li>
                <%= link_to new_user_session_path, class:"nav-link text-light" do %>
                  <i class="fa-solid fa-sign-in-alt"></i>
                  Log in
                <% end %>
              </li>
              
              
              <% end %>
              
            </ul>
        </div>
    </nav>
  </header>
  <%= flash[:notice] %>
    <%= yield %>
    
    
    
    <footer>
    <div class="contaniner mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
  
    
    
  </body>
  
  
</html>

app/views/users/_list.html.erb
<!-- ユーザーの詳細 -->
<!-- @user → user -->
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <h2> User info</h2> 
  <%= image_tag user.get_profile_image(100,100) %>
  
 <table class="table">
   <tbody>
       <th>name</th>
       <th><%= user.name %></th>
     </tr>
     <tr>
       <th>introduction</th>
     <th><%= user.introduction %></th>
     </tr>
   </tbody>
   </table>

   <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
  

<!-- 投稿機能 -->

<h1>New book</h1>
<%= form_with model: book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body%>
  <div class="form-group">
      <input type="submit" name="commint" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
  </div>
<% end %>

app/views/users/edit.html.erb
  <p id="notice"></p>
  <div class="container">
  <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h2>User info</h2>
  
  <% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  
<%= form_with model: @user do |f| %>
<div class="form-group">
  <label for="Name">Name</label>
  </div>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <div class="form-group"><label for="inputImage">Image</label></div>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>  
 <div class="form-group"> 
 <label for="user_introduction">Introduction</label>
 <%= f.text_field :introduction %>
 </div>
  <div>
  <%= f.submit "Update User", class:"btn btn-secondary"%>
  </div>
  
<% end %>
</div>
</div>
</div>

app/views/users/index.html.erb
<main>
<div class="container px-5 px-sm-0">
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'list', user: @user, book: @book%>
    </div>
    <div class="col-md-8 offset-md-1">
      <!-- ユーザーの投稿一覧 -->

      <h1>Users</h1>
      <table class="table table-hover table-inverse">
          <thead>
              <tr>
                  <th>image</th>
                  <th>name</th>
                  <th></th>
                  <th colspan="3"></th>
              </tr>
              </thead>
              
              
              <tbody>
                  
      <% @users.each do |user| %>
      
      <tr>
        <%= link_to user_path(user.id) do %>
          <!--%= image_tag book.get_image %-->
        <% end %>
        <td><%= image_tag user.get_profile_image(100,100) %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
      <% end %>
      
      </tbody>
      </table>
    </div>
  </div>
</div>
</div>
</main>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'list', user: @user, book: @book%>
    </div>
    <div class="col-md-8 offset-md-1">
      <!-- ユーザーの投稿一覧 -->

      <h1>Books</h1>
      <table class="table table-hover table-inverse">
          <thead>
              <tr>
                  <th></th>
                  <th>Title</th>
                  <th>Opinion</th>
                  <th colspan="3"></th>
              </tr>
              </thead>
              
              
              <tbody>
                  
      <% @books.each do |book| %>
      
      <tr>
        <%= link_to user_path(@user.id) do %>
        <td><%= image_tag book.user.get_profile_image(100,100) %></td>
        <% end %>
        <td><%=link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
        </tr>
      <% end %>
      
      </tbody>
      </table>
    </div>
  </div>
</div>